### ISSUE TITLE
Using Liquid within an anchor tag?

### ISSUE THREAD

**Issue by FlyersPh9** [bradfrost/style-guide-guide#33]
I am editing **button.md** and **component-detail.html**.  In the  **button.md** file I am creating a new variable called _yammer_.

```
fine-print:
- version: 0.3
  update: April 27, 2017
  owner: Jane Doe
  yammer:  http://github.com
```

In the **component-detail.html** file I am trying to use the _yammer_ variable in an anchor tag like this:
```
<ul>
  <li>Yammer: {{ print.yammer }}</li>
</ul>
<a href="{{ print.yammer }}" class="c-btn">Discuss this on Yammer</a>
```

When the page renders, Yammer's value does appear in the unordered list, but does not appear within the anchor tag.  Any ideas how to get this to work?
